#!/usr/bin/python3

print('Content-Type: text/plain\r')
print('\r')
print('This is my test!')
print('이것도 바디')
print('저것도 바디')
print('여기까지 :) 바디바디\n바디바디 당근당근🥕\n')
print('예지는 포스트만 보내')
print('네 ^^ㄱ')
print('이제 되겠지?')